name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"

      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m unittest
        continue-on-error: true

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@v2
        if: success() || failure()
